server:
  port: 9099

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/products/**
          
        
        
        
        
        
          